(cl:defpackage human_navigation-msg
  (:use )
  (:export
   "<HUMANNAVIAVATARPOSE>"
   "HUMANNAVIAVATARPOSE"
   "<HUMANNAVIGUIDANCEMSG>"
   "HUMANNAVIGUIDANCEMSG"
   "<HUMANNAVIMSG>"
   "HUMANNAVIMSG"
   "<HUMANNAVIOBJECTINFO>"
   "HUMANNAVIOBJECTINFO"
   "<HUMANNAVITASKINFO>"
   "HUMANNAVITASKINFO"
  ))

