# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from human_navigation/HumanNaviAvatarPose.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class HumanNaviAvatarPose(genpy.Message):
  _md5sum = "da17fe0a6c6bd33b9ccc614a3a7af77c"
  _type = "human_navigation/HumanNaviAvatarPose"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Pose head
geometry_msgs/Pose left_hand
geometry_msgs/Pose right_hand

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['head','left_hand','right_hand']
  _slot_types = ['geometry_msgs/Pose','geometry_msgs/Pose','geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       head,left_hand,right_hand

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HumanNaviAvatarPose, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.head is None:
        self.head = geometry_msgs.msg.Pose()
      if self.left_hand is None:
        self.left_hand = geometry_msgs.msg.Pose()
      if self.right_hand is None:
        self.right_hand = geometry_msgs.msg.Pose()
    else:
      self.head = geometry_msgs.msg.Pose()
      self.left_hand = geometry_msgs.msg.Pose()
      self.right_hand = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_21d().pack(_x.head.position.x, _x.head.position.y, _x.head.position.z, _x.head.orientation.x, _x.head.orientation.y, _x.head.orientation.z, _x.head.orientation.w, _x.left_hand.position.x, _x.left_hand.position.y, _x.left_hand.position.z, _x.left_hand.orientation.x, _x.left_hand.orientation.y, _x.left_hand.orientation.z, _x.left_hand.orientation.w, _x.right_hand.position.x, _x.right_hand.position.y, _x.right_hand.position.z, _x.right_hand.orientation.x, _x.right_hand.orientation.y, _x.right_hand.orientation.z, _x.right_hand.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.head is None:
        self.head = geometry_msgs.msg.Pose()
      if self.left_hand is None:
        self.left_hand = geometry_msgs.msg.Pose()
      if self.right_hand is None:
        self.right_hand = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 168
      (_x.head.position.x, _x.head.position.y, _x.head.position.z, _x.head.orientation.x, _x.head.orientation.y, _x.head.orientation.z, _x.head.orientation.w, _x.left_hand.position.x, _x.left_hand.position.y, _x.left_hand.position.z, _x.left_hand.orientation.x, _x.left_hand.orientation.y, _x.left_hand.orientation.z, _x.left_hand.orientation.w, _x.right_hand.position.x, _x.right_hand.position.y, _x.right_hand.position.z, _x.right_hand.orientation.x, _x.right_hand.orientation.y, _x.right_hand.orientation.z, _x.right_hand.orientation.w,) = _get_struct_21d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_21d().pack(_x.head.position.x, _x.head.position.y, _x.head.position.z, _x.head.orientation.x, _x.head.orientation.y, _x.head.orientation.z, _x.head.orientation.w, _x.left_hand.position.x, _x.left_hand.position.y, _x.left_hand.position.z, _x.left_hand.orientation.x, _x.left_hand.orientation.y, _x.left_hand.orientation.z, _x.left_hand.orientation.w, _x.right_hand.position.x, _x.right_hand.position.y, _x.right_hand.position.z, _x.right_hand.orientation.x, _x.right_hand.orientation.y, _x.right_hand.orientation.z, _x.right_hand.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.head is None:
        self.head = geometry_msgs.msg.Pose()
      if self.left_hand is None:
        self.left_hand = geometry_msgs.msg.Pose()
      if self.right_hand is None:
        self.right_hand = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 168
      (_x.head.position.x, _x.head.position.y, _x.head.position.z, _x.head.orientation.x, _x.head.orientation.y, _x.head.orientation.z, _x.head.orientation.w, _x.left_hand.position.x, _x.left_hand.position.y, _x.left_hand.position.z, _x.left_hand.orientation.x, _x.left_hand.orientation.y, _x.left_hand.orientation.z, _x.left_hand.orientation.w, _x.right_hand.position.x, _x.right_hand.position.y, _x.right_hand.position.z, _x.right_hand.orientation.x, _x.right_hand.orientation.y, _x.right_hand.orientation.z, _x.right_hand.orientation.w,) = _get_struct_21d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_21d = None
def _get_struct_21d():
    global _struct_21d
    if _struct_21d is None:
        _struct_21d = struct.Struct("<21d")
    return _struct_21d
