// Generated by gencpp from file human_navigation/HumanNaviTaskInfo.msg
// DO NOT EDIT!


#ifndef HUMAN_NAVIGATION_MESSAGE_HUMANNAVITASKINFO_H
#define HUMAN_NAVIGATION_MESSAGE_HUMANNAVITASKINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <human_navigation/HumanNaviObjectInfo.h>
#include <human_navigation/HumanNaviObjectInfo.h>
#include <geometry_msgs/Point.h>

namespace human_navigation
{
template <class ContainerAllocator>
struct HumanNaviTaskInfo_
{
  typedef HumanNaviTaskInfo_<ContainerAllocator> Type;

  HumanNaviTaskInfo_()
    : environment_id()
    , objects_info()
    , target_object()
    , destination()  {
    }
  HumanNaviTaskInfo_(const ContainerAllocator& _alloc)
    : environment_id(_alloc)
    , objects_info(_alloc)
    , target_object(_alloc)
    , destination(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _environment_id_type;
  _environment_id_type environment_id;

   typedef std::vector< ::human_navigation::HumanNaviObjectInfo_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::human_navigation::HumanNaviObjectInfo_<ContainerAllocator> >::other >  _objects_info_type;
  _objects_info_type objects_info;

   typedef  ::human_navigation::HumanNaviObjectInfo_<ContainerAllocator>  _target_object_type;
  _target_object_type target_object;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _destination_type;
  _destination_type destination;





  typedef boost::shared_ptr< ::human_navigation::HumanNaviTaskInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::human_navigation::HumanNaviTaskInfo_<ContainerAllocator> const> ConstPtr;

}; // struct HumanNaviTaskInfo_

typedef ::human_navigation::HumanNaviTaskInfo_<std::allocator<void> > HumanNaviTaskInfo;

typedef boost::shared_ptr< ::human_navigation::HumanNaviTaskInfo > HumanNaviTaskInfoPtr;
typedef boost::shared_ptr< ::human_navigation::HumanNaviTaskInfo const> HumanNaviTaskInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::human_navigation::HumanNaviTaskInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::human_navigation::HumanNaviTaskInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace human_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'human_navigation': ['/home/kamerider/catkin_ws/src/Simulation-interactive_clean up/human-navigation-ros/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::human_navigation::HumanNaviTaskInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_navigation::HumanNaviTaskInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::human_navigation::HumanNaviTaskInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::human_navigation::HumanNaviTaskInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_navigation::HumanNaviTaskInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_navigation::HumanNaviTaskInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::human_navigation::HumanNaviTaskInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a171437ef155a1af48679c78f18cbc7d";
  }

  static const char* value(const ::human_navigation::HumanNaviTaskInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa171437ef155a1afULL;
  static const uint64_t static_value2 = 0x48679c78f18cbc7dULL;
};

template<class ContainerAllocator>
struct DataType< ::human_navigation::HumanNaviTaskInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "human_navigation/HumanNaviTaskInfo";
  }

  static const char* value(const ::human_navigation::HumanNaviTaskInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::human_navigation::HumanNaviTaskInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string environment_id\n\
HumanNaviObjectInfo[] objects_info\n\
HumanNaviObjectInfo target_object\n\
geometry_msgs/Point destination\n\
\n\
================================================================================\n\
MSG: human_navigation/HumanNaviObjectInfo\n\
string name\n\
geometry_msgs/Point position\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::human_navigation::HumanNaviTaskInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::human_navigation::HumanNaviTaskInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.environment_id);
      stream.next(m.objects_info);
      stream.next(m.target_object);
      stream.next(m.destination);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HumanNaviTaskInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::human_navigation::HumanNaviTaskInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::human_navigation::HumanNaviTaskInfo_<ContainerAllocator>& v)
  {
    s << indent << "environment_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.environment_id);
    s << indent << "objects_info[]" << std::endl;
    for (size_t i = 0; i < v.objects_info.size(); ++i)
    {
      s << indent << "  objects_info[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::human_navigation::HumanNaviObjectInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.objects_info[i]);
    }
    s << indent << "target_object: ";
    s << std::endl;
    Printer< ::human_navigation::HumanNaviObjectInfo_<ContainerAllocator> >::stream(s, indent + "  ", v.target_object);
    s << indent << "destination: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.destination);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMAN_NAVIGATION_MESSAGE_HUMANNAVITASKINFO_H
