// Generated by gencpp from file human_navigation/HumanNaviAvatarPose.msg
// DO NOT EDIT!


#ifndef HUMAN_NAVIGATION_MESSAGE_HUMANNAVIAVATARPOSE_H
#define HUMAN_NAVIGATION_MESSAGE_HUMANNAVIAVATARPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace human_navigation
{
template <class ContainerAllocator>
struct HumanNaviAvatarPose_
{
  typedef HumanNaviAvatarPose_<ContainerAllocator> Type;

  HumanNaviAvatarPose_()
    : head()
    , left_hand()
    , right_hand()  {
    }
  HumanNaviAvatarPose_(const ContainerAllocator& _alloc)
    : head(_alloc)
    , left_hand(_alloc)
    , right_hand(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _head_type;
  _head_type head;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _left_hand_type;
  _left_hand_type left_hand;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _right_hand_type;
  _right_hand_type right_hand;





  typedef boost::shared_ptr< ::human_navigation::HumanNaviAvatarPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::human_navigation::HumanNaviAvatarPose_<ContainerAllocator> const> ConstPtr;

}; // struct HumanNaviAvatarPose_

typedef ::human_navigation::HumanNaviAvatarPose_<std::allocator<void> > HumanNaviAvatarPose;

typedef boost::shared_ptr< ::human_navigation::HumanNaviAvatarPose > HumanNaviAvatarPosePtr;
typedef boost::shared_ptr< ::human_navigation::HumanNaviAvatarPose const> HumanNaviAvatarPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::human_navigation::HumanNaviAvatarPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::human_navigation::HumanNaviAvatarPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace human_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'human_navigation': ['/home/kamerider/catkin_ws/src/human-navigation-ros/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::human_navigation::HumanNaviAvatarPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_navigation::HumanNaviAvatarPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::human_navigation::HumanNaviAvatarPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::human_navigation::HumanNaviAvatarPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_navigation::HumanNaviAvatarPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_navigation::HumanNaviAvatarPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::human_navigation::HumanNaviAvatarPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da17fe0a6c6bd33b9ccc614a3a7af77c";
  }

  static const char* value(const ::human_navigation::HumanNaviAvatarPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda17fe0a6c6bd33bULL;
  static const uint64_t static_value2 = 0x9ccc614a3a7af77cULL;
};

template<class ContainerAllocator>
struct DataType< ::human_navigation::HumanNaviAvatarPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "human_navigation/HumanNaviAvatarPose";
  }

  static const char* value(const ::human_navigation::HumanNaviAvatarPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::human_navigation::HumanNaviAvatarPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose head\n\
geometry_msgs/Pose left_hand\n\
geometry_msgs/Pose right_hand\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::human_navigation::HumanNaviAvatarPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::human_navigation::HumanNaviAvatarPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.head);
      stream.next(m.left_hand);
      stream.next(m.right_hand);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HumanNaviAvatarPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::human_navigation::HumanNaviAvatarPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::human_navigation::HumanNaviAvatarPose_<ContainerAllocator>& v)
  {
    s << indent << "head: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.head);
    s << indent << "left_hand: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.left_hand);
    s << indent << "right_hand: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.right_hand);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMAN_NAVIGATION_MESSAGE_HUMANNAVIAVATARPOSE_H
